baseURL = "https://cadence.link/"
languageCode = "en-us"
title = "cadence.link"
disableKinds = ["taxonomy", "term", "RSS"]
enableGitInfo = true

[params]
  author = "CloudMax"
  authorlink = "https://twitter.com/CloudMax94/"
  github = "https://github.com/CloudMax94/cadence.link"
  favicon = "/favicon.ico"

[frontmatter]
  lastmod = [":git"]

[markup]
  [markup.goldmark]
    [markup.goldmark.renderer]
      hardWraps = true
      unsafe = true

[menu]
  [[menu.other]]
    name = "Discord"
    url = "https://discord.gg/VtdN3PZ"
    weight = 1
  [[menu.other]]
    name = "CoNDOR"
    url = "https://condor.live/"
    weight = 2
  [[menu.other]]
    name = "SRC Leaderboards"
    url = "https://coh-boards.deku.link/"
    weight = 3
  [[menu.other]]
    name = "Skips and Strats Sheet"
    url = "https://deku.link/cohstrats"
    weight = 4
  [[menu.main]]
    parent = "tech"
    name = "Version 1.4"
    weight = 94000
  [[menu.main]]
    parent = "tech"
    name = "Version 1.4 - 1.1"
    weight = 95000
  [[menu.main]]
    parent = "tech"
    name = "Version 1.1"
    weight = 96000
  [[menu.main]]
    parent = "tech"
    name = "Version 1.1 & 1.0"
    weight = 97000
  [[menu.main]]
    parent = "tech"
    name = "Version 1.0"
    weight = 98000
  [[menu.main]]
    parent = "tech"
    name = "Version 1.0.0 & 1.0.1"
    weight = 99000
  [[menu.main]]
    parent = "overworld"
    name = "POIs"
    weight = 1
  [[menu.main]]
    parent = "overworld"
    name = "Biomes"
    weight = 1000
  [[menu.main]]
    parent = "overworld"
    name = "Mapping"
    weight = 2000
